<?php
	echo "<font color=black face='Georgia'>";
	echo "<Biodata>";
	echo "<b>";
	echo "<h2>";
	echo "<center>";
	echo "Biodata";
	echo "</h2>";
	echo "<br>";
	echo "<hr>";
	echo "<center>";
	echo "<table width='500' border='0'>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Nama";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "MUH TAUFIQ";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Stambuk";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "182273";
			echo "</td>";
		echo "</tr>";
		echo "<tr>";
			echo "<td>";
				echo "&nbsp;";
			echo "</td>";
			echo "<td>";
				echo "Kelas";
			echo "</td>";
			echo "<td>";
				echo ":";
			echo "</td>";
			echo "<td>";
				echo "F-6TCLC";
			echo "</td>";
		echo "</table>";
		echo "<hr>";

?>
